# Generated by tools/package_release.ts for v0.1.0-alpha.7. Do not edit by hand.
#
# The hashes below are the ones in that release's signed SHA256SUMS manifest,
# so installing through Homebrew pins the same artefact the release evidence
# covers. Verify the release itself with tools/verify-release.sh.
class Egrysa < Formula
  desc "Customer-owned AI egress boundary with signed, content-free receipts"
  homepage "https://github.com/Intellumia/egrysa"
  version "0.1.0-alpha.7"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/Intellumia/egrysa/releases/download/v0.1.0-alpha.7/egrysa-v0.1.0-alpha.7-aarch64-apple-darwin.tar.gz"
      sha256 "19b52f9647582968f9092c0c5d8c98e3735149394ca4108f556f53b6d8668df7"
    end
    on_intel do
      url "https://github.com/Intellumia/egrysa/releases/download/v0.1.0-alpha.7/egrysa-v0.1.0-alpha.7-x86_64-apple-darwin.tar.gz"
      sha256 "eb93f8e190fe0eb71d52b8f1a7d12b38faba9c371feaf4f587bc540345a12488"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Intellumia/egrysa/releases/download/v0.1.0-alpha.7/egrysa-v0.1.0-alpha.7-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "4b31b5081efa82d41354aba1dd8a96a89d8c0643cf71997564ac43d4bb570f17"
    end
    on_intel do
      url "https://github.com/Intellumia/egrysa/releases/download/v0.1.0-alpha.7/egrysa-v0.1.0-alpha.7-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "2cd5c73adbb3b60cdf84070f8ce418043ef659aaddba99447b257cc07292ef2f"
    end
  end

  def install
    bin.install "egrysa"
    # The gateway will not start without a configuration; ship the examples
    # where an operator can find and copy them.
    pkgshare.install "config"
    doc.install "README.md"
  end

  def caveats
    <<~EOS
      Egrysa needs a configuration file and its own keys. To start from the example:

        mkdir -p ~/.egrysa && cp #{pkgshare}/config/egrysa.example.json ~/.egrysa/egrysa.json
        EGRYSA_CONFIG=~/.egrysa/egrysa.json egrysa

      Generate keys with the repository's keygen tool, and read
      https://github.com/Intellumia/egrysa/blob/v0.1.0-alpha.7/docs/OPERATIONS.md
      before exposing the listener to anything but loopback.
    EOS
  end

  test do
    assert_match "egrysa", shell_output("#{bin}/egrysa --version 2>&1", 0)
  end
end
