// Generate the package-manager metadata for a published release.
//
// Homebrew and npm both install a binary by URL and a hash. Those hashes
// exist only once a release has been built, and they must be the hashes the
// signed SHA256SUMS manifest already covers, so this reads that manifest
// rather than recomputing anything. Run it after `tools/verify-release.sh`
// has passed, never before: the point is that what a package manager pins is
// an artefact whose signature was checked.
//
//   deno task package:release --tag=v0.1.0-alpha.7 --sums=./evidence/SHA256SUMS
//
// It writes Formula/egrysa.rb (the Homebrew formula, served from this
// repository as its own tap) and packaging/npm/manifest.json (the version and
// per-platform hashes the npm wrapper verifies a download against).

interface Options {
  tag: string;
  sums: string;
  root: string;
}

const TARGETS: Record<string, { os: "darwin" | "linux"; cpu: "arm64" | "x64" }> = {
  "aarch64-apple-darwin": { os: "darwin", cpu: "arm64" },
  "x86_64-apple-darwin": { os: "darwin", cpu: "x64" },
  "aarch64-unknown-linux-gnu": { os: "linux", cpu: "arm64" },
  "x86_64-unknown-linux-gnu": { os: "linux", cpu: "x64" },
};

function parse(argv: string[]): Options {
  const options: Options = { tag: "", sums: "", root: "." };
  for (const arg of argv) {
    if (arg === "--") continue;
    const separator = arg.indexOf("=");
    const name = separator < 0 ? arg : arg.slice(0, separator);
    const value = separator < 0 ? "" : arg.slice(separator + 1);
    if (name === "--tag") options.tag = value;
    else if (name === "--sums") options.sums = value;
    else if (name === "--root") options.root = value;
    else {
      console.error(`unknown argument: ${arg}`);
      Deno.exit(2);
    }
  }
  if (!/^v\d+\.\d+\.\d+(-[0-9A-Za-z.]+)?$/.test(options.tag) || !options.sums) {
    console.error("usage: package_release.ts --tag=vX.Y.Z[-pre] --sums=PATH [--root=DIR]");
    Deno.exit(2);
  }
  return options;
}

const options = parse(Deno.args);
const version = options.tag.replace(/^v/, "");
const base = `https://github.com/Intellumia/egrysa/releases/download/${options.tag}`;

// "<sha256>  <filename>" per line, as sha256sum writes it.
const hashes = new Map<string, string>();
for (const line of (await Deno.readTextFile(options.sums)).split("\n")) {
  const match = line.match(/^([0-9a-f]{64})\s+\*?(.+)$/);
  if (match) hashes.set(match[2]!.trim().split("/").pop()!, match[1]!);
}

const assets = Object.entries(TARGETS).map(([target, platform]) => {
  const file = `egrysa-${options.tag}-${target}.tar.gz`;
  const sha256 = hashes.get(file);
  if (!sha256) {
    console.error(`${file} is not in ${options.sums}; build the release first`);
    Deno.exit(1);
  }
  return { target, ...platform, file, sha256, url: `${base}/${file}` };
});

// Homebrew. The formula lives in this repository, so a tap needs no second
// repository: `brew tap intellumia/egrysa https://github.com/Intellumia/egrysa`.
const byPlatform = (os: string, cpu: string) =>
  assets.find((asset) => asset.os === os && asset.cpu === cpu)!;
const formula = `# Generated by tools/package_release.ts for ${options.tag}. Do not edit by hand.
#
# The hashes below are the ones in that release's signed SHA256SUMS manifest,
# so installing through Homebrew pins the same artefact the release evidence
# covers. Verify the release itself with tools/verify-release.sh.
class Egrysa < Formula
  desc "Customer-owned AI egress boundary with signed, content-free receipts"
  homepage "https://github.com/Intellumia/egrysa"
  version "${version}"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "${byPlatform("darwin", "arm64").url}"
      sha256 "${byPlatform("darwin", "arm64").sha256}"
    end
    on_intel do
      url "${byPlatform("darwin", "x64").url}"
      sha256 "${byPlatform("darwin", "x64").sha256}"
    end
  end

  on_linux do
    on_arm do
      url "${byPlatform("linux", "arm64").url}"
      sha256 "${byPlatform("linux", "arm64").sha256}"
    end
    on_intel do
      url "${byPlatform("linux", "x64").url}"
      sha256 "${byPlatform("linux", "x64").sha256}"
    end
  end

  def install
    bin.install "egrysa"
    # The gateway will not start without a configuration; ship the examples
    # where an operator can find and copy them.
    pkgshare.install "config"
    doc.install "README.md"
  end

  def caveats
    <<~EOS
      Egrysa needs a configuration file and its own keys. To start from the example:

        mkdir -p ~/.egrysa && cp #{pkgshare}/config/egrysa.example.json ~/.egrysa/egrysa.json
        EGRYSA_CONFIG=~/.egrysa/egrysa.json egrysa

      Generate keys with the repository's keygen tool, and read
      https://github.com/Intellumia/egrysa/blob/${options.tag}/docs/OPERATIONS.md
      before exposing the listener to anything but loopback.
    EOS
  end

  test do
    assert_match "egrysa", shell_output("#{bin}/egrysa --version 2>&1", 0)
  end
end
`;

const manifest = {
  version,
  tag: options.tag,
  // The npm wrapper downloads the platform's tarball and refuses to install
  // unless it hashes to the value below.
  binaries: Object.fromEntries(
    assets.map((asset) => [`${asset.os}-${asset.cpu}`, {
      url: asset.url,
      sha256: asset.sha256,
      file: asset.file,
    }]),
  ),
};

await Deno.mkdir(`${options.root}/Formula`, { recursive: true });
await Deno.writeTextFile(`${options.root}/Formula/egrysa.rb`, formula);
await Deno.writeTextFile(
  `${options.root}/packaging/npm/manifest.json`,
  `${JSON.stringify(manifest, null, 2)}\n`,
);

const packageJsonPath = `${options.root}/packaging/npm/package.json`;
const packageJson = JSON.parse(await Deno.readTextFile(packageJsonPath)) as { version: string };
packageJson.version = version;
await Deno.writeTextFile(packageJsonPath, `${JSON.stringify(packageJson, null, 2)}\n`);

console.log(JSON.stringify(
  {
    tag: options.tag,
    version,
    wrote: ["Formula/egrysa.rb", "packaging/npm/manifest.json", "packaging/npm/package.json"],
    assets: assets.map((asset) => ({ file: asset.file, sha256: asset.sha256 })),
  },
  null,
  2,
));
